// frontend/src/components/navbar.vue
<template>
  <div>
    <b-navbar bg="transparent" expand="lg" variant="light" class="navbar" fixed="top">
      <Sidebar />
      <b-container fluid>
        <b-navbar-brand href="/">
          <img
            src="https://cdn.discordapp.com/attachments/1110232564624539700/1110910397038460998/Zara-Logo.png"
            style="margin-left: 100px; width: 200px; height: 90px"
          />
        </b-navbar-brand>

        <b-navbar-toggle target="navbarScroll" />

        <b-collapse id="navbarScroll" is-nav>
          <b-nav class="me-auto my-2 my-lg-0" style="max-height: 100px" navbar-scroll>
            <b-nav-item href="/" style="font-size: 15px; margin-left: 20px"></b-nav-item>
          </b-nav>

          <div>
            <b-nav-item href="/Search" style="color: #212529; font-family: Helvetica Neue; font-size: 12px; margin-right: 20px; text-decoration: underline">
              SEARCH
            </b-nav-item>
          </div>

          <div>
            <b-nav-item href="/login" style="color: #212529; font-family: Helvetica Neue; font-size: 12px">
              LOG IN
            </b-nav-item>
          </div>

          <div>
            <b-nav-item href="/help" style="color: #212529; font-family: Helvetica Neue; font-size: 12px; margin-left: 20px">
              HELP
            </b-nav-item>
          </div>

          <svg class="layout-header-shop-cart-link__icon" style="margin-right: 20px" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="inherit" stroke="inherit">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M9.708 5a2.5 2.5 0 0 1 4.584 0H9.708zM8.645 5a3.502 3.502 0 0 1 6.71 0H19v15H5V5h3.645zM6 6v13h12V6H6z"></path>
          </svg>
        </b-collapse>
      </b-container>
    </b-navbar>
  </div>
</template>

<script>
import { BNavbar, BNavbarBrand, BNavbarToggle, BCollapse, BNav, BNavItem, BContainer } from 'bootstrap-vue';
import Sidebar from './sidbar.vue';
import {defineComponent} from "vue"

export default defineComponent({
  components: {
    BNavbar,
    BNavbarBrand,
    BNavbarToggle,
    BCollapse,
    BNav,
    BNavItem,
    BContainer,
    Sidebar
  }
});
</script>
<style scoped>
.navbar {
  background-color: transparent;
}

.navbar-brand img {
  margin-left: 100px;
  width: 200px;
  height: 90px;
}

.nav-link {
  color: #212529;
  font-family: Helvetica Neue;
  font-size: 12px;
  margin-right: 20px;
  text-decoration: none;
}

.nav-link:hover {
  text-decoration: underline
}

.layout-header-shop-cart-link__icon {
  margin-right: 20px;
}


</style>

// client/pages/component/navBar.tsx
import React from 'react';
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import Sidebar from '../Sidebar';

const NavBar = () => {
  return (
    <div>
      <Navbar bg="transparent" expand="lg" variant="light" className="navbares" fixed="top">
      
        <Sidebar  />
        <Container fluid>
        
          <Navbar.Brand href="/">
            <img
              src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Zara_Logo.svg/2560px-Zara_Logo.svg.png"
              style={{ marginLeft: "100px", width: "200px", height: "90px" }}
            />
          </Navbar.Brand>

        
          <Navbar.Toggle aria-controls="navbarScroll" />
          <Navbar.Collapse id="navbarScroll">
            <Nav className="me-auto my-2 my-lg-0" style={{ maxHeight: '100px' }} navbarScroll>
              <Nav.Link
                href="/"
                style={{
                  color: "black",
                  fontFamily: "Sans-serif",
                  fontSize: "15px",
                  marginLeft: "50px",
                }}
              >
                
              </Nav.Link>
            </Nav>

            <div>
              <Nav.Link
                href="/search"
                style={{
                fontFamily: "Arial, Helvetica, sans-serif", fontSize: "17px",
                  marginRight: "60px",
                  //textDecoration: "underline",
                }}
              >
              
                Search
              </Nav.Link>
            </div>

            <div>
              <Nav.Link href="/login" style={{ fontFamily: "Arial, Helvetica, sans-serif", fontSize: "15px" }}>
                SIGN IN
              </Nav.Link>
            </div>

            <div>
              <Nav.Link
                href="/details"
                style={{
                    fontFamily: "Arial, Helvetica, sans-serif", fontSize: "17px",
                  marginLeft: "70px",
                }}
              >
               Collection
              </Nav.Link>
            </div>
            <div>
            <Nav.Link
                href="/cart" 
            >
            <img 
              src="https://cdn.discordapp.com/attachments/1073948141822427256/1108700360891183175/aFtEKyQmH8K26qurE22yD-transformed.png"
              style={{ marginLeft: "40px", width: "40px", height: "40px" }}
            />
            </Nav.Link>
            </div>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </div>
  );
};

export default NavBar;
